### ISSUE TITLE
Font type of text lines in logo

### ISSUE THREAD

**Issue by xgenvn** [ythecombinator/You-Dont-Know-X#4]
Hi,

I would love to know which font type you use for text lines in logo.

Thanks.

**Comment by ythecombinator** [comment]
Hey, such a great question. It'd be nice to include credits for this amazing font.

It's called [Monoid](https://github.com/larsenwork/monoid) and it's actually a *ligatures-based* font which I use when coding. 

> I'll credit it in future updates.

**Comment by ythecombinator** [comment]
I think that's it haha.
